### ISSUE TITLE
CMD files / hard coded drive F:

### ISSUE THREAD

**Issue by ourIThome** [M1kerochip/LaunchGreaseWeazle#2]
I just stumbled across your project... Just taking a small peek at the code (waiting on 2004 update for Windows 10).  Looks like the CMD files are hard coded drive letter / path.  I haven't looked deeply at the source code, so you might change this on the fly... Just thought I'd ask the question.

**Comment by M1kerochip** [comment]
Thanks for looking! (Never noticed the issue had been opened until now, sorry!)

Yes, they're just examples, that I use myself.
I have no intention of creating a full blown program, and including the required files.
(HxC Floppy Emulator, nConvert, disk-utils (disk-analyse) + SPS dll, Aufit for Atari ST images, etc)


Quick edit: I misunderstood.
